### ISSUE TITLE
.NET debugger fails to install because naming convetion for assets seems to have changed

### ISSUE THREAD

**Issue by kolpav** [Pocco81/DAPInstall.nvim#13]
```
--2021-08-04 10:48:01--  https://github.com/Samsung/netcoredbg/releases/latest/download/netcoredbg-linux-bionic-amd64.tar.gz
Resolving github.com (github.com)... 140.82.121.3
Connecting to github.com (github.com)|140.82.121.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://github.com/Samsung/netcoredbg/releases/download/1.2.0-825/netcoredbg-linux-bionic-amd64.tar.gz [following]
--2021-08-04 10:48:01--  https://github.com/Samsung/netcoredbg/releases/download/1.2.0-825/netcoredbg-linux-bionic-amd64.tar.gz
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 404 Not Found
2021-08-04 10:48:02 ERROR 404: Not Found.


[Process exited 8]
```

<img width="1127" alt="image" src="https://user-images.githubusercontent.com/19467143/128151858-deaed958-3575-4cba-9419-a67cacbde5ad.png">

**Comment by Pocco81** [comment]
Fixed! Btw, I don't do any .NET dev so if you could report back to see if the default config works it'd be awesome!

**Comment by kolpav** [comment]
@Pocco81 Installation passed but I can't debug most probably because I don't know what I am doing its my first time using DAP. Are my assumptions correct?

You need to have `mfussenegger/nvim-dap` and `Pocco81/DAPInstall.nvim` installed

Have this in your lua config which will load configs for installed debuggers maintained by this repo. Great for people who don't know what they are doing (me).

```lua
local dap_install = require("dap-install")
local dbg_list = require("dap-install.debuggers_list").debuggers

for debugger, _ in pairs(dbg_list) do
	dap_install.config(debugger, {})
end
```

Then run `:lua require'dap'.continue()` and you should be good right?

If thats the case I am getting 

<img width="662" alt="image" src="https://user-images.githubusercontent.com/19467143/128247177-12a76426-4078-41be-a6e6-6d0a5464d219.png">

I was prompted to enter built .dll path which I think I entered correctly.

The minimal debug check should be easy to do even when you are not .net dev here are instructions if you ever wanted to do that.

1. [Download](https://dotnet.microsoft.com/download) .net sdk
2. Create hello world project `dotnet new console -o DapDebugTest`
3. `cd DapDebugTest` and `dotnet build` to build debug dlls or `dotnet run` to restore (something like npm install) + build + run

With that being said feel free to ping me in the future with .net related stuff I'll be happy to help. This project is great it has same feel as https://github.com/kabouzeid/nvim-lspinstall nobody wants to fiddle with setting lsp or debug configs when vscode from which many are people moving to nvim has it set up by default or one "install" click away from their extension store. Nvim is getting closer to same experience thanks to projects as yours which are super valuable but at the same time exhausting to maintain as one name change in release file breaks whole debugger install with no fault of yours so you are more likely to collect issues than PRs so thanks for this project 👍

**Comment by Pocco81** [comment]
> Are my assumptions correct?

Yep, you did everything correctly.

> If thats the case I am getting
My bad, sorry! this was caused because I passed the wrong param to the degubber (`"file"` instead of `${file}`), just fixed it. Could you test it and report back again so that we can mark it as "tested" in the debuggers list?

> Nvim is getting closer to same experience thanks to projects as yours which are super valuable

Thanks man! I really appreciate it :) Yeah it's hard to maintain/develop projects like this. Sure the core is done and can be improved over time, but without the debuggers themselves it's kinda useless and since we are talking about debuggers I can't test every single one them and small errors like this one above (passing a wrong param in the debugger's config) can be overlooked. 

I'm currently working on [MerelyFmt.nvim](https://github.com/Pocco81/MerelyFmt.nvim/tree/dev) btw, which has the goal of making formatter/formatting code accessible and without too much hassle. Similar to how DAPInstall.nvim makes debuggers/debugging more accessible.

**Comment by kolpav** [comment]
@Pocco81 I am on mac and it seems linux version is hardcoded in downloaded link and for latest version of `netcoredbg` there isn't even mac version for some reason while older releases have it so I downloaded release with mac version still present and extracted it into `/Users/kolpav/.local/share/nvim/dapinstall/dnetcs_dbg/netcoredbg` on first run I also needed to allow it in "Security & Privacy" after that it seems to be working. `MerelyFmt.nvim` looks really cool good luck with it.

**Comment by Pocco81** [comment]
Could you pass me the commands you used to install the debugger?

**Comment by kolpav** [comment]
There are no commands it was done manually I downloaded [1.2.0-786 for mac](https://github.com/Samsung/netcoredbg/releases/download/1.2.0-786/netcoredbg-osx.tar.gz) and put in place where `DAPInstall` expects to find runnable `netcoredbg`.

> Sadly I think that's out of the scope of DAPInstall.nvim.

Sure it wasn't meant as request I just wanted to provide all the steps I needed to take.

**Comment by Pocco81** [comment]
Okay, DAPInstall should now be able to detect the OS accordingly and fetch the appropriate archive :+1:

**Comment by kolpav** [comment]
@Pocco81 Just letting you know that installation now indeed passes on macos.
